 // Sample data - replace with your actual data
  const data = [
    {
      id: 1,
      fullname: "FGFC19",
      memberId: "FGFC19",
      totalActiveDirects: 1,
      password: "******",
      systemPackage: "900000",
      sponsorId: "SP123",
      sponsorName: "John Doe",
      mobileNumber: "+1234567890",
      activationDate: "2024-02-10",
      registrationDate: "2024-02-01",
      kycStatus: "Verified",
      bankStatus: "Verified",
      userStatus: "Active",
      pinStatus: "ON",
      levelManual: "Level OFF",
    },
    {
      id: 2,
      fullname: "Jane Smith",
      memberId: "FGFC20",
      totalActiveDirects: 3,
      password: "******",
      systemPackage: "950000",
      sponsorId: "SP124",
      sponsorName: "Alice Williams",
      mobileNumber: "+1234567891",
      activationDate: "2024-02-08",
      registrationDate: "2024-01-20",
      kycStatus: "Verified",
      bankStatus: "Verified",
      userStatus: "Active",
      pinStatus: "ON",
      levelManual: "Level ON",
    },
    {
      id: 3,
      fullname: "Mark Johnson",
      memberId: "FGFC21",
      totalActiveDirects: 2,
      password: "******",
      systemPackage: "920000",
      sponsorId: "SP125",
      sponsorName: "Bob Brown",
      mobileNumber: "+1234567892",
      activationDate: "2024-02-09",
      registrationDate: "2024-01-22",
      kycStatus: "Verified",
      bankStatus: "Pending",
      userStatus: "Inactive",
      pinStatus: "OFF",
      levelManual: "Level OFF",
    },
    {
      id: 4,
      fullname: "Emily Davis",
      memberId: "FGFC22",
      totalActiveDirects: 0,
      password: "******",
      systemPackage: "850000",
      sponsorId: "SP126",
      sponsorName: "Charlie White",
      mobileNumber: "+1234567893",
      activationDate: "2024-02-07",
      registrationDate: "2024-01-25",
      kycStatus: "Pending",
      bankStatus: "Pending",
      userStatus: "Inactive",
      pinStatus: "OFF",
      levelManual: "Level OFF",
    },
    {
      id: 5,
      fullname: "Sophia Martinez",
      memberId: "FGFC23",
      totalActiveDirects: 5,
      password: "******",
      systemPackage: "1000000",
      sponsorId: "SP127",
      sponsorName: "David Green",
      mobileNumber: "+1234567894",
      activationDate: "2024-02-05",
      registrationDate: "2024-01-18",
      kycStatus: "Verified",
      bankStatus: "Verified",
      userStatus: "Active",
      pinStatus: "ON",
      levelManual: "Level ON",
    },
    {
      id: 6,
      fullname: "William Moore",
      memberId: "FGFC24",
      totalActiveDirects: 1,
      password: "******",
      systemPackage: "910000",
      sponsorId: "SP128",
      sponsorName: "Sarah Lee",
      mobileNumber: "+1234567895",
      activationDate: "2024-02-06",
      registrationDate: "2024-01-30",
      kycStatus: "Verified",
      bankStatus: "Verified",
      userStatus: "Active",
      pinStatus: "ON",
      levelManual: "Level ON",
    },
    {
      id: 7,
      fullname: "Olivia Taylor",
      memberId: "FGFC25",
      totalActiveDirects: 4,
      password: "******",
      systemPackage: "980000",
      sponsorId: "SP129",
      sponsorName: "Michael Scott",
      mobileNumber: "+1234567896",
      activationDate: "2024-02-04",
      registrationDate: "2024-01-15",
      kycStatus: "Verified",
      bankStatus: "Verified",
      userStatus: "Active",
      pinStatus: "ON",
      levelManual: "Level OFF",
    },
  ];

  export default data;